/** Dedicated metadata schema. No source/body/content column or runtime DDL privilege. */
export const HANA_SCHEMA_VERSION = 1;
export const HANA_TABLE_DDL = [
  `CREATE COLUMN TABLE SCHEMA_MIGRATIONS (VERSION INTEGER PRIMARY KEY, APPLIED_AT TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL)`,
  `CREATE ROW TABLE COLLECTOR_LOCK (ID INTEGER PRIMARY KEY, REVISION BIGINT DEFAULT 0 NOT NULL)`,
  `INSERT INTO COLLECTOR_LOCK(ID) VALUES (1)`,
  `CREATE COLUMN TABLE NODES (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SYSTEM_KEY NVARCHAR(128) NOT NULL,
    OBJECT_TYPE NVARCHAR(40) NOT NULL,
    OBJECT_NAME NVARCHAR(255) NOT NULL,
    PACKAGE_NAME NVARCHAR(255) DEFAULT '' NOT NULL,
    DESCRIPTION NVARCHAR(1024) DEFAULT '' NOT NULL,
    LOCATOR NVARCHAR(1024),
    RESOLUTION_STATUS NVARCHAR(20) NOT NULL,
    UNIQUE(SYSTEM_KEY, OBJECT_TYPE, OBJECT_NAME),
    CHECK (RESOLUTION_STATUS IN ('resolved', 'unresolved', 'out_of_scope'))
  )`,
  `CREATE INDEX NODES_NAME_IDX ON NODES(SYSTEM_KEY, OBJECT_NAME, OBJECT_TYPE)`,
  `CREATE COLUMN TABLE EDGE_OBSERVATIONS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOURCE_NODE_ID BIGINT NOT NULL REFERENCES NODES(ID),
    TARGET_NODE_ID BIGINT NOT NULL REFERENCES NODES(ID),
    RELATION_KIND NVARCHAR(40) NOT NULL,
    EVIDENCE_OWNER NVARCHAR(512) NOT NULL,
    EVIDENCE_METHOD NVARCHAR(128) NOT NULL,
    SOURCE_RESOURCE NVARCHAR(1024) NOT NULL,
    UNIQUE(SOURCE_NODE_ID, TARGET_NODE_ID, RELATION_KIND, EVIDENCE_OWNER, EVIDENCE_METHOD, SOURCE_RESOURCE),
    CHECK (RELATION_KIND IN ('belongs_to', 'inherits_from', 'implements', 'references', 'static_call',
      'function_call', 'reads_from', 'projects_on', 'associates_to', 'composes'))
  )`,
  `CREATE INDEX EDGE_OUTGOING_IDX ON EDGE_OBSERVATIONS(SOURCE_NODE_ID, RELATION_KIND, TARGET_NODE_ID)`,
  `CREATE INDEX EDGE_INCOMING_IDX ON EDGE_OBSERVATIONS(TARGET_NODE_ID, RELATION_KIND, SOURCE_NODE_ID)`,
  `CREATE COLUMN TABLE GENERATIONS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SYSTEM_KEY NVARCHAR(128) NOT NULL,
    SCOPE_NAME NVARCHAR(1024) NOT NULL,
    EXTRACTOR_VERSION NVARCHAR(128) NOT NULL,
    STATUS NVARCHAR(20) NOT NULL,
    COMPLETED_AT TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL,
    COUNTERS NVARCHAR(5000),
    CHECK (STATUS IN ('complete', 'partial'))
  )`,
  `CREATE COLUMN TABLE COLLECTION_JOBS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GENERATION_ID BIGINT NOT NULL REFERENCES GENERATIONS(ID),
    CHECKPOINT NCLOB NOT NULL
  )`,
  `INSERT INTO SCHEMA_MIGRATIONS(VERSION) VALUES (1)`,
] as const;
