import type { AdtClient } from '../adt/client.js';

/** Reviewed plain-read API, shared by the public type and runtime facade. Never infer this
 * surface from all AdtClient methods: that class also has writes, SQL and raw session access. */
export const READ_ONLY_CLIENT_KEYS = [
  'username',
  'usesBearerAuth',
  'sapClient',
  'getProgram',
  'getSourceAtObjectUrl',
  'getClass',
  'getClassInclude',
  'getClassMetadata',
  'getClassStructured',
  'getClassStructure',
  'getInterface',
  'getFunction',
  'getFunctionModuleProperties',
  'resolveFunctionGroup',
  'getFunctionGroup',
  'getFunctionGroupSource',
  'getInclude',
  'getFunctionGroupExpanded',
  'getDdls',
  'getDcl',
  'getBdef',
  'getSrvd',
  'getKtd',
  'getDdlx',
  'getSrvb',
  'getTable',
  'getView',
  'getStructure',
  'getTabl',
  'resolveTablObjectUrl',
  'getDomain',
  'getTableType',
  'getDataElement',
  'getAuthorizationField',
  'getRevisions',
  'getRevisionSource',
  'getFeatureToggle',
  'getEnhancementImplementation',
  'getTransaction',
  'getApiReleaseState',
  'getInactiveObjects',
  'searchObject',
  'lookupObjects',
  'searchSource',
  'getPackageContents',
  'getSubpackages',
  'getEffectiveUser',
  'getSystemInfo',
  'getInstalledComponents',
  'getMessages',
  'getMessageClassInfo',
  'getTextElements',
  'getTextElementPart',
  'getClassTextSymbols',
  'getVariants',
  'listBspApps',
  'getBspAppStructure',
  'getBspFileContent',
  'getBspPathContent',
  'getObjectMetadata',
  'resolveObjectPackage',
] as const satisfies readonly (keyof AdtClient)[];

export type ReadOnlyAdtClient = Readonly<Pick<AdtClient, (typeof READ_ONLY_CLIENT_KEYS)[number]>>;
